// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Test$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Test";
  readonly sourceName: "contracts/Test.sol";
  readonly abi: [{"inputs":[],"name":"x","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f80fd5b5060ac8061001b5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c80630c55699c14602a575b5f80fd5b60306044565b604051603b9190605f565b60405180910390f35b5f5481565b5f819050919050565b6059816049565b82525050565b5f60208201905060705f8301846052565b9291505056fea26469706673582212206b1170d8784386badde4fe974ec9b598632d8697f00d9c063f9580e8678ac3bc64736f6c63430008140033";
  readonly deployedBytecode: "0x6080604052348015600e575f80fd5b50600436106026575f3560e01c80630c55699c14602a575b5f80fd5b60306044565b604051603b9190605f565b60405180910390f35b5f5481565b5f819050919050565b6059816049565b82525050565b5f60208201905060705f8301846052565b9291505056fea26469706673582212206b1170d8784386badde4fe974ec9b598632d8697f00d9c063f9580e8678ac3bc64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Test.sol";
  readonly buildInfoId: "solc-0_8_20-eb0d464e03e1491b9b6e68d52723a3f0a954600e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Test"]: Test$Type;
    ["contracts/Test.sol:Test"]: Test$Type;
  }
}